### PR TITLE
add local quote testing

### PR DESCRIPTION
**Pull request by andrewsource147**

### CODE REVIEW

**Comment by codewithgun** [comment]
Could you add the test into the CI? Thanks.

**Comment by codewithgun** [comment]
Could you group all the `.bin` files under it's associated market folder? Eg: `EtAdVRLFH22rjWh3mcUasKFF27WtHhsaCvK27tPFFWig` folder. In case, we need to test other market in the future.

**Comment by andrewsource147** [comment]
> Could you group all the `.bin` files under it's associated market folder? Eg: `EtAdVRLFH22rjWh3mcUasKFF27WtHhsaCvK27tPFFWig` folder. In case, we need to test other market in the future.

fixed

**Comment by andrewsource147** [comment]
> Could you add the test into the CI? Thanks.

added

**Review by codewithgun — APPROVED** [review]

**Pull request merged**
