### PR TITLE
Fix empty reward claims

### PR DESCRIPTION
**Pull request by shadeglare**
This patch excludes positions without any fees and/or rewards from the `claimAllRewards` method.

### CODE REVIEW

**Comment by shadeglare** [comment]
> Looks good! Do you mind bump the sdk version in package.json & update the changelog?

Bumped the sdk version to `1.0.48`. Where should I put the changelog? Thanks.

**Comment by 00xSam** [comment]
> > Looks good! Do you mind bump the sdk version in package.json & update the changelog?
> 
> Bumped the sdk version to `1.0.48`. Where should I put the changelog? Thanks.

https://github.com/MeteoraAg/dlmm-sdk/blob/main/CHANGELOG.md

**Comment by shadeglare** [comment]
> > > Looks good! Do you mind bump the sdk version in package.json & update the changelog?
> > 
> > 
> > Bumped the sdk version to `1.0.48`. Where should I put the changelog? Thanks.
> 
> https://github.com/MeteoraAg/dlmm-sdk/blob/main/CHANGELOG.md

Done.

**Review by 00xSam — APPROVED** [review]
LGTM

**Comment by 00xSam** [comment]
There are conflicts

**Comment by shadeglare** [comment]
> There are conflicts

Resolved as of now.

**Comment by 00xSam** [comment]
@shadeglare I've published `@meteora-ag/dlmm@1.0.48`, thanks for your contributions

**Pull request merged**
